### ISSUE TITLE
PurePerm addon

### ISSUE THREAD

**Issue by efor89** [provsalt/ScoreHud-AddonX#1]
hi
can you make one for pureperm too?

**Comment by efor89** [comment]
and i have internal server error if i use setmoney or givemoney 

Error: "Call to undefined method onebone\economyapi\event\money\MoneyChangedEvent::getNewMoney()" (EXCEPTION) in "plugins/economy-hud_dev-4.phar/src/provsalt/scorehud/economyhud/events/ChangeListener" at line 18

**Comment by provsalt** [comment]
> and i have internal server error if i use setmoney or givemoney
> 
> Error: "Call to undefined method onebone\economyapi\event\money\MoneyChangedEvent::getNewMoney()" (EXCEPTION) in "plugins/economy-hud_dev-4.phar/src/provsalt/scorehud/economyhud/events/ChangeListener" at line 18

make sure you are on the newest version of economyapi

**Comment by efor89** [comment]
ok the newest version work thx

**Comment by efor89** [comment]
the new scorehud version is rly good :)

**Comment by efor89** [comment]
internal server error and server crash if i use setmoney for an offline player

020-10-04 [06:49:06] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to Ifera\ScoreHud\event\ScoreHudEvent::__construct() must be an instance of pocketmine\Player, null given, called in phar://C:/Users/....../Desktop/PocketMine-MP-minigames-hub/plugins/economy-hud_dev-4.phar/src/provsalt/scorehud/economyhud/events/ChangeListener.php on line 18" (EXCEPTION) in "plugins/ScoreHud_dev-48.phar/src/Ifera/ScoreHud/event/ScoreHudEvent" at line 50
2020-10-04 [06:49:06] [Server thread/CRITICAL]: #0 plugins/economy-hud_dev-4.phar/src/provsalt/scorehud/economyhud/events/ChangeListener(18): Ifera\ScoreHud\event\ScoreHudEvent->__construct(NULL , object Ifera\ScoreHud\scoreboard\ScoreTag)
